name: First Github Action

on:
  pull_request:
  push:
  
jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v1
      - uses: hmarr/auto-approve-action@v4
      - name: go-mnd
        uses: tommy-muehle/go-mnd@v2.5.1
            
